version: "3.7"
services:
    vector-db:
        image: redis/redis-stack:latest
        ports:
            - 6379:6379
            - 8001:8001
        environment:
            - REDISEARCH_ARGS=CONCURRENT_WRITE_MODE
        volumes:
            - vector-db:/var/lib/redis
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        healthcheck:
            test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
            interval: 2s
            timeout: 1m30s
            retries: 5
            start_period: 5s
        networks:
            - redis-net
    backend:
        image: sjkchang/hackathon-backend
        ports:
            - 5000:5000
        environment:
            - REDIS_HOST=vector-db
            - REDIS_PORT=6379
            - REDIS_PASSWORD="password"
            - OPENAI_API_KEY=<YOUR_OPENAI_API_KEY>
        depends_on:
            - vector-db
        networks:
            - redis-net

volumes:
    vector-db:
networks:
    redis-net:
        driver: bridge
